baseURL = "https://guide.pkmn.no/"
languageCode = "NB-no"
title = "[pkmn.no] Samlerguiden"
theme = "hugo-theme-learn"
defaultContentLanguage = "no"
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "pkmn"
  landingPageURL = "https://pkmn.no"
  landingPageName = "<i class='fas fa-home'></i> Hjem"
[outputs]
  home = [ "HTML", "RSS", "JSON"]
[[menu.shortcuts]]
name = "<i class='fas fa-camera'></i> Kortopedia"
url = "https://pkmn.no/sets"
weight = 11
