baseURL = "https://guide.pkmn.no/"
languageCode = "NB-no"
title = "[pkmn.no]"
theme = "hugo-theme-learn"
defaultContentLanguage = "no"
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "pkmn"
  landingPageURL = "/"
  landingPageName = "<i class='fas fa-home'></i> Pok√©mon-samlekortguiden"
[outputs]
  home = [ "HTML", "RSS", "JSON"]
[[menu.shortcuts]]
name = "<i class='fas fa-camera'></i> Kortopedia"
url = "https://pkmn.no/sets"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-home'></i> pkmn.no"
url = "https://pkmn.no/"
weight = 1
